### ISSUE TITLE
Remove polyfill.io - distributes malware

### ISSUE THREAD

**Issue by asche77** [hl2guide/AdGuard-Home-Whitelist#11]
### Checklist

- [X] This is not a **[duplicate](https://github.com/hl2guide/AdGuard-Home-Whitelist/issues)** of an existing issue.

### Description

Remove cdn.polyfill.io ( @@|cdn.polyfill.io^$important ) from whitelist.

It distributes malware (recent development).

See https://sansec.io/research/polyfill-supply-chain-attack (or any other Google search for "malware polyfill.io") 

### Expected behaviour

Don't whitelist cdn.polyfill.io.

### Current behaviour

Whitelisted.

### Steps to reproduce

Dig CDN.polyfill.io

**Comment by hl2guide** [comment]
Thanks for letting me know I'll fix that now. Fixed 😃
