### ISSUE TITLE
Whitelist for full functionality for Facebook and Facebook Messenger

### ISSUE THREAD

**Issue by Clyde6790pGIT** [hl2guide/AdGuard-Home-Whitelist#13]
### Checklist

- [X] This is not a **[duplicate](https://github.com/hl2guide/AdGuard-Home-Whitelist/issues)** of an existing issue.

### Description

Facebook and Facebook Messenger refuse to function as multiple of their domains are blocked by filters.

### Possible reason/solution

By adding this to the whitelist, it should work fine.
@@||upload.facebook.com^$important
@@||creative.ak.fbcdn.net^$important
@@||external-lhr0-1.xx.fbcdn.net^$important
@@||external-lhr1-1.xx.fbcdn.net^$important
@@||external-lhr10-1.xx.fbcdn.net^$important
@@||external-lhr2-1.xx.fbcdn.net^$important
@@||external-lhr3-1.xx.fbcdn.net^$important
@@||external-lhr4-1.xx.fbcdn.net^$important
@@||external-lhr5-1.xx.fbcdn.net^$important
@@||external-lhr6-1.xx.fbcdn.net^$important
@@||external-lhr7-1.xx.fbcdn.net^$important
@@||external-lhr8-1.xx.fbcdn.net^$important
@@||external-lhr9-1.xx.fbcdn.net^$important
@@||fbcdn-creative-a.akamaihd.net^$important
@@||scontent-lhr3-1.xx.fbcdn.net^$important
@@||scontent.xx.fbcdn.net^$important
@@||scontent.fgdl5-1.fna.fbcdn.net^$important
@@||graph.facebook.com^$important
@@||b-graph.facebook.com^$important
@@||connect.facebook.com^$important
@@||cdn.fbsbx.com^$important
@@||api.facebook.com^$important
@@||edge-mqtt.facebook.com^$important
@@||mqtt.c10r.facebook.com^$important
@@||portal.fb.com^$important
@@||star.c10r.facebook.com^$important
@@||star-mini.c10r.facebook.com^$important
@@||fb.me^$important
@@||bigzipfiles.facebook.com^$important
@@||l.facebook.com^$important
@@||www.facebook.com^$important
@@||scontent-atl3-1.xx.fbcdn.net^$important
@@||static.xx.fbcdn.net^$important
@@||edge-chat.messenger.com^$important
@@||video.xx.fbcdn.net^$important
@@||external-ort2-1.xx.fbcdn.net^$important
@@||scontent-ort2-1.xx.fbcdn.net^$important 
@@||edge-chat.facebook.com^$important
@@||scontent-mia3-1.xx.fbcdn.net^$important
@@||web.facebook.com^$important
@@||rupload.facebook.com^$important
@@||b-api.facebook.com^$important
@@||l.messenger.com^$important
@@||gateway.facebook.com^$important

### Additional information

We sadly cannot avoid graph.facebook.com tracker here as they are needed for login and authentication for both Facebook and Facebook Messenger app, these domains were tested by me and a lot of them are vital for functionality for either app, "external" may be possibly used for images.
Sourced from: https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212

**Comment by hl2guide** [comment]
I intentionally block Facebook and similar sites to protect user security.

Please whitelist manually if desired, knowing the risks in doing so.
