### ISSUE TITLE
Apple Captive Portal Test (Wifi Login Test)

### ISSUE THREAD

**Issue by Clyde6790pGIT** [hl2guide/AdGuard-Home-Whitelist#14]
### Checklist

- [X] This is not a **[duplicate](https://github.com/hl2guide/AdGuard-Home-Whitelist/issues)** of an existing issue.

### Description

These domains are needed for an Apple device to determine if they are being held behind a captive portal (aka Wifi Login Page) and need sign in, if these are not whitelisted, the device may attempt to open a login page on a network with no additional login pages for wifi access.

### Possible reason/solution

By whitelisting the following, it should work fine.
@@||captive.apple.com^$important
@@||gsp1.apple.com^$important
@@||www.apple.com^$important
@@||www.appleiphonecell.com^$important

### Additional information

I sourced these with my own testing, and later found it included as well on a community edited whitelist for PiHole.
https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212

**Comment by Clyde6790pGIT** [comment]
> ### Checklist
> 
>     * [x]  This is not a **[duplicate](https://github.com/hl2guide/AdGuard-Home-Whitelist/issues)** of an existing issue.
> 
> 
> ### Description
> 
> These domains are needed for an Apple device to determine if they are being held behind a captive portal (aka Wifi Login Page) and need sign in, if these are not whitelisted, the device may attempt to open a login page on a network with no additional login pages for wifi access.
> ### Possible reason/solution
> 
> By whitelisting the following, it should work fine. @@||captive.apple.com^$important @@||gsp1.apple.com^$important @@||www.apple.com^$important @@||www.appleiphonecell.com^$important
> ### Additional information
> 
> I sourced these with my own testing, and later found it included as well on a community edited whitelist for PiHole. https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212

www.appleiphonecell.com and possibly the other domains excluding www.apple.com just return a "Success" screen.

**Comment by hl2guide** [comment]
Please refer to the README:

"What's Not Whitelisted 🛑
🍏 Apple products or services"

Please add manually.
