### ISSUE TITLE
Make a version without porn whitelisted

### ISSUE THREAD

**Issue by Clyde6790pGIT** [hl2guide/AdGuard-Home-Whitelist#15]
### Checklist

- [X] This is not a **[duplicate](https://github.com/hl2guide/AdGuard-Home-Whitelist/issues)** of an existing issue.
- [X] I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.

### Purpose

I'd like a version with no porn sites whitelisted as I don't want any of my young siblings to be connecting to these platforms.

### Solution

Make a version without porn

### Why are the currently available solutions not sufficient?

Even with a lot of porn filters on my installation, this whitelist just allows them to be viewed.

**Comment by Clyde6790pGIT** [comment]
I'm also wondering why the main page doesn't mention this either, shouldn't it mention it?

**Comment by hl2guide** [comment]
> I'm also wondering why the main page doesn't mention this either, shouldn't it mention it?

The page `USAGE.md` covers using this as modular form: https://github.com/hl2guide/AdGuard-Home-Whitelist/blob/main/USAGE.md

see: https://github.com/hl2guide/AdGuard-Home-Whitelist/blob/main/MODULES.md

it's more fiddly and manual.

In general I recommend that you read this too about the `important` modifier: https://adguard-dns.io/kb/general/dns-filtering-syntax/#important-modifier ($important in rules)

It is meant to function that way so if it is not, please report the bug to AdGuard Home when you confirm it.

For example:

"Custom filtering rules"

```
||pornhub.com^$important
||www.pornhub.com^$important
```

**Comment by Clyde6790pGIT** [comment]
Why are all the other modules on the main page tho? I didn't spot the adult website whitelist since I was expecting it to be mentioned in the main page like most of the other modules, but I have removed it by manually adding all the modules except that
