### ISSUE TITLE
Whitelist roblox, rules are in desc

### ISSUE THREAD

**Issue by Big-Dawgs** [hl2guide/AdGuard-Home-Whitelist#2]
@@|www.roblox.com^$important
@@|clientsettingscdn.roblox.com^$important
@@|locale.roblox.com^$important
@@|api.roblox.com^$important
@@|fra2-128-116-123-3.roblox.com^$important
@@|games.roblox.com^$important
@@|accountinformation.roblox.com^$important
@@|friends.roblox.com^$important
@@|accountsettings.roblox.com^$important
@@|thumbnails.roblox.com^$important
@@|lms.roblox.com^$important
@@|assestdelivery.roblox.com^$important
@@|abtesting.roblox.com^$important
@@|apis.roblox.com^$important
@@|ephemeralcounters.api.roblox.com^$important
@@|atl1-128-116-99-3.roblox.com^$important
@@|ams1-128-116-121-3.roblox.com^$important
@@|iad4-128-116-102-3.roblox.com^$important
@@|sea1-128-116-100-3.roblox.com^$important
@@|ash1-128-116-114-3.roblox.com^$important
@@|realtime.roblox.com^$important
@@|presence.roblox.com^$important
@@|auth.roblox.com^$important
@@|economy.roblox.com^$important
@@|catalog.roblox.com^$important
@@|notifications.roblox.com^$important
@@|contacts.roblox.com^$important
@@|chat.roblox.com^$important
@@|badges.roblox.com^$important
@@|followings.roblox.com^$important
Note: dont whitelist roblox.com, this will let in potential ads and trackers, this is why its www.roblox.com

**Comment by hl2guide** [comment]
thanks for submitting this, I'll check it around mid-January 2022 in the next code review.
