### ISSUE TITLE
1.1 Finalized and 1.2 Upcoming

### ISSUE THREAD

**Issue by hl2guide** [hl2guide/AdGuard-Home-Whitelist#3]
I cleaned up this repo and finalized version 1.1.

The upcoming version 1.2 is:
* focused on optional modules (whitelist.txt will remain an all-in-one default)
* scheduled to release in late January 2022. 🤞

**Comment by hl2guide** [comment]
Rescheduled this to late January 2022, to do more testing.

**Comment by HowWof** [comment]
Take your time and thanks for the very good whitelist.

**Comment by hl2guide** [comment]
Should be ready by 21 Jan 2022. 🦆

**Comment by hl2guide** [comment]
Version 1.2 is out! 🎉
