### ISSUE TITLE
Add to whitelist

### ISSUE THREAD

**Issue by HowWof** [hl2guide/AdGuard-Home-Whitelist#4]
Hi
Please add these domains to the whitelist
u1595434.ct.sendgrid.net (used by universities in Poland to give licenses for programs like Cad
stats.lvlup.pro (used to see uptime of vps servers on lvlup.pro)
interia.hit.gemius.pl (tracking link without it you won't be able to log in to Interia.pl mail)
cert.pl (security and lists against spam or malware)
Proserwer.pl (hosting domains and vps servers)

**Comment by hl2guide** [comment]
I'll consider putting these in a "Poland" list in the future.
