### ISSUE TITLE
Remove from list

### ISSUE THREAD

**Issue by HowWof** [hl2guide/AdGuard-Home-Whitelist#5]
### Checklist

- [X] This is not a **[duplicate](https://github.com/hl2guide/AdGuard-Home-Whitelist/issues)** of an existing issue.

### Description

While running, Brave will make lots of requests to the domain p3a.brave.com as telemetry. They claim they store the collected data for several days.
Brave has a rewards program.At first glance it looks like the rewards program is an opt-in, but the browser makes requests to these domains regardless if you sign up or not:
rewards.brave.com
api.rewards.brave.com
grant.rewards.brave.com
Brave on first run sends a request to fetch the library used for checking spelling errors:
variations.brave.com
Brave fetches the list of affiliates through 
laptop-updates.brave.com
Brave makes a request to static1.brave.com every once and a while, which looks like it's used to fetch plugin information?
When the url was placed into the browser, it was directed to Google's error 404 page
On the first run, Brave fetches five extensions from brave-core-ext.s3.brave.com and tries to install them

### Expected behaviour

Remove this spying domain 

### Current behaviour

Spaying domen being whitelisted 

### Steps to reproduce

Run brave

**Comment by hl2guide** [comment]
okay, thanks for posting this 😁

I'll look into this soon and make modifications if needed.

**Comment by hl2guide** [comment]
fixed now.
