### ISSUE TITLE
Protectstar.com should be whitelisted

### ISSUE THREAD

**Issue by Big-Dawgs** [hl2guide/AdGuard-Home-Whitelist#6]
### Checklist

- [X] This is not a **[duplicate](https://github.com/hl2guide/AdGuard-Home-Whitelist/issues)** of an existing issue.

### Description

*Protectstar™* is a security company that made anti-virus and anti spy apps for Android
Incl. *Anti-virus AI®, Anti-spy®, iShedder®* etc.

They are featured in *USA Today, Bild, CNN Underscored, CNN Money*.

By blocking this site, potentially it will cause API to break and updating malware database definitions will not be possible. It can be possible that some trackers may be included in subdomains, but that is up to you to figure that out. But I don't think there are trackers based on what they made.

**What was I going to do?:** I was going to update malware database definitions on my phone, but instead it said, *error occurred, please try again*, and I can't access the main page.

If there is something important that I am missing out on, please let me know.

### Expected behaviour

I expected that I can normally update the malware database and access the product page without problems.

### Current behaviour

Instead the API domain (api.protectstar.com) has been blocked and caused the malware database updates to stop working, and because the main domain isn't whitelisted, I can't access the main page either.

### Steps to reproduce

**For reproducing steps for broken malware database**
Step 1. Go to Play Store
Step 2. Search (pub: Protectstar Inc).
Step 3. Find the app named *Antivirus AI*
Step 4. Download it.
Step 5. Set it up
Step 6. In settings (to clarify, it is in the anti-virus app), go to device immunity & click check.
It will show up as *Error occurred, please try again*

**For reproducing steps for broken main page**
Step 1. Use a formal browser (for example: Chrome).
Step 2. Go to www.protectstar.com
It will show up as a NXDOMAIN or DNS refused page.

### Possible reason/solution

Whitelisting the domains www.protectstar.com & api.protectstar.com, but I can also suggest to whitelist the whole domain, I can't see a reason why a security company that made products like Camera Guard would just track & spy on consumers, I even checked logs to see what they had, may not be keen but I didn't see any trackers & ads so far.

### Additional information

**How I am using this on my phone you may ask?** 
Well you see, I'm using an AdGuard Android client software for this, and I am just using this whitelist as a whitelist for prevention of broken domains and links & even potentially some core functions of some applications.

**Comment by hl2guide** [comment]
Thanks for the detailed report. I'll consider it after looking into it some more as I've never personally known of that company.

Generally I suggest that you consider my list as a good starting point to running in whitelisting mode.

Please manually whitelist to your hearts content to suit your situation.

When I add domains to my list files I consider "is the average person needing this" and more often the answer is "No".

**Comment by hl2guide** [comment]
After review I've decided to classify this as a custom manual whitelisting situation instead of including it.
